//! Subgroup lattice: lattice of subgroups of an agent group.
//!
//! The subgroups of a group, ordered by inclusion, form a lattice where
//! join = subgroup generated by union, meet = intersection.

use serde::{Serialize, Deserialize};
use std::collections::BTreeSet;
use crate::lattice::{FiniteLattice, LatticeElement};

/// An element of a finite group represented as a permutation or by generators.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct GroupElement {
    /// The permutation in one-line notation (0-indexed).
    pub perm: Vec<usize>,
}

impl GroupElement {
    /// Create identity permutation of degree n.
    pub fn identity(n: usize) -> Self {
        Self { perm: (0..n).collect() }
    }

    /// Create from slice.
    pub fn from_slice(perm: &[usize]) -> Self {
        Self { perm: perm.to_vec() }
    }

    /// Compose two permutations: (self)(other).
    pub fn compose(&self, other: &Self) -> Self {
        Self {
            perm: self.perm.iter().map(|&i| other.perm[i]).collect(),
        }
    }

    /// Inverse permutation.
    pub fn inverse(&self) -> Self {
        let mut inv = vec![0; self.perm.len()];
        for (i, &p) in self.perm.iter().enumerate() {
            inv[p] = i;
        }
        Self { perm: inv }
    }

    /// Order of this element.
    pub fn order(&self) -> usize {
        let mut current = self.clone();
        let id = Self::identity(self.perm.len());
        for i in 1..=self.perm.len().factorial() {
            if current == id { return i; }
            current = current.compose(self);
        }
        self.perm.len() // fallback
    }

    /// Degree of the permutation.
    pub fn degree(&self) -> usize {
        self.perm.len()
    }
}

trait Factorial {
    fn factorial(&self) -> usize;
}

impl Factorial for usize {
    fn factorial(&self) -> usize {
        (1..=*self).product()
    }
}

/// A subgroup of a permutation group, defined by a set of elements.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Subgroup {
    /// Label for this subgroup.
    pub label: String,
    /// Elements in the subgroup (sorted for deterministic comparison).
    pub elements: BTreeSet<Vec<usize>>,
}

impl Subgroup {
    pub fn new(label: impl Into<String>, elements: &[GroupElement]) -> Self {
        let set: BTreeSet<Vec<usize>> = elements.iter().map(|e| e.perm.clone()).collect();
        Self { label: label.into(), elements: set }
    }

    /// The trivial subgroup {identity}.
    pub fn trivial(n: usize) -> Self {
        Self::new("trivial", &[GroupElement::identity(n)])
    }

    /// Order (number of elements).
    pub fn order(&self) -> usize {
        self.elements.len()
    }

    /// Check if this subgroup contains another (inclusion).
    pub fn contains_subgroup(&self, other: &Subgroup) -> bool {
        other.elements.iter().all(|e| self.elements.contains(e))
    }

    /// Intersection of two subgroups (meet in the subgroup lattice).
    pub fn intersection(&self, other: &Subgroup) -> Subgroup {
        let elems: BTreeSet<Vec<usize>> = self.elements.intersection(&other.elements).cloned().collect();
        Subgroup {
            label: format!("{}∩{}", self.label, other.label),
            elements: elems,
        }
    }

    /// Generate subgroup from a set of generators by closure.
    pub fn generate(generators: &[GroupElement], label: impl Into<String>) -> Self {
        let n = generators.first().map(|g| g.degree()).unwrap_or(0);
        let id = GroupElement::identity(n);
        let mut group: BTreeSet<Vec<usize>> = BTreeSet::new();
        group.insert(id.perm.clone());

        let mut changed = true;
        while changed {
            changed = false;
            let current: Vec<GroupElement> = group.iter()
                .map(|p| GroupElement { perm: p.clone() })
                .collect();
            for elem in &current {
                for gen in generators {
                    let prod = elem.compose(gen);
                    if !group.contains(&prod.perm) {
                        group.insert(prod.perm);
                        changed = true;
                    }
                    let prod2 = gen.compose(elem);
                    if !group.contains(&prod2.perm) {
                        group.insert(prod2.perm);
                        changed = true;
                    }
                }
            }
        }

        Subgroup { label: label.into(), elements: group }
    }
}

/// Lattice of subgroups of a group.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubgroupLattice {
    /// The full group elements.
    group_elements: Vec<GroupElement>,
    /// All subgroups.
    subgroups: Vec<Subgroup>,
    /// The underlying lattice structure.
    lattice: FiniteLattice,
}

impl SubgroupLattice {
    /// Build the subgroup lattice from a list of subgroups.
    pub fn from_subgroups(subgroups: Vec<Subgroup>) -> Self {
        let mut lattice = FiniteLattice::new();

        for sg in &subgroups {
            lattice.add_element(LatticeElement::new(&sg.label));
        }

        // Set join/meet based on inclusion
        for i in 0..subgroups.len() {
            for j in 0..subgroups.len() {
                let a = &subgroups[i];
                let b = &subgroups[j];

                // Meet = intersection
                let meet = a.intersection(b);
                // Find the subgroup matching the intersection
                if let Some(m) = subgroups.iter().find(|s| s.elements == meet.elements) {
                    lattice.set_meet(&a.label, &b.label, &m.label);
                }

                // Join = smallest subgroup containing both (generated)
                let gens_a: Vec<GroupElement> = a.elements.iter()
                    .map(|p| GroupElement { perm: p.clone() })
                    .collect();
                let gens_b: Vec<GroupElement> = b.elements.iter()
                    .map(|p| GroupElement { perm: p.clone() })
                    .collect();
                let mut all_gens: Vec<GroupElement> = gens_a;
                all_gens.extend(gens_b);
                let joined = Subgroup::generate(&all_gens, "temp");
                if let Some(j) = subgroups.iter().find(|s| s.elements == joined.elements) {
                    lattice.set_join(&a.label, &b.label, &j.label);
                }
            }
        }

        // Covers
        for i in 0..subgroups.len() {
            for j in 0..subgroups.len() {
                if i != j && subgroups[i].contains_subgroup(&subgroups[j]) {
                    let mut is_cover = true;
                    for k in 0..subgroups.len() {
                        if k != i && k != j &&
                           subgroups[i].contains_subgroup(&subgroups[k]) &&
                           subgroups[k].contains_subgroup(&subgroups[j]) {
                            is_cover = false;
                            break;
                        }
                    }
                    if is_cover {
                        lattice.add_cover(&subgroups[j].label, &subgroups[i].label);
                    }
                }
            }
        }

        // Find trivial and full group
        if let Some(trivial) = subgroups.iter().find(|s| s.order() == 1) {
            lattice.set_bottom(&trivial.label);
        }
        if let Some(full) = subgroups.iter().max_by_key(|s| s.order()) {
            lattice.set_top(&full.label);
        }

        let group_elements = subgroups.iter()
            .max_by_key(|s| s.order())
            .map(|s| s.elements.iter().map(|p| GroupElement { perm: p.clone() }).collect())
            .unwrap_or_default();

        Self { group_elements, subgroups, lattice }
    }

    pub fn lattice(&self) -> &FiniteLattice {
        &self.lattice
    }

    pub fn subgroups(&self) -> &[Subgroup] {
        &self.subgroups
    }

    /// The subgroup lattice of S₃ (symmetric group on 3 elements).
    /// S₃ has subgroups: {e}, <(12)>, <(13)>, <(23)>, <(123)>, S₃
    pub fn s3_subgroup_lattice() -> Self {
        let id = GroupElement::identity(3);
        // (12)
        let t12 = GroupElement::from_slice(&[1, 0, 2]);
        // (13)
        let t13 = GroupElement::from_slice(&[2, 1, 0]);
        // (23)
        let t23 = GroupElement::from_slice(&[0, 2, 1]);
        // (123)
        let c123 = GroupElement::from_slice(&[1, 2, 0]);
        // (132)
        let c132 = GroupElement::from_slice(&[2, 0, 1]);

        let trivial = Subgroup::new("trivial", &[id.clone()]);
        let s_t12 = Subgroup::new("<(12)>", &[id.clone(), t12.clone()]);
        let s_t13 = Subgroup::new("<(13)>", &[id.clone(), t13.clone()]);
        let s_t23 = Subgroup::new("<(23)>", &[id.clone(), t23.clone()]);
        let a3 = Subgroup::new("A₃", &[id.clone(), c123.clone(), c132.clone()]);
        let s3 = Subgroup::new("S₃", &[id, t12, t13, t23, c123, c132]);

        Self::from_subgroups(vec![trivial, s_t12, s_t13, s_t23, a3, s3])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_identity_permutation() {
        let id = GroupElement::identity(3);
        assert_eq!(id.perm, vec![0, 1, 2]);
    }

    #[test]
    fn test_compose_permutations() {
        let a = GroupElement::from_slice(&[1, 2, 0]); // (123)
        let b = GroupElement::from_slice(&[1, 0, 2]); // (12)
        let ab = a.compose(&b);
        assert_eq!(ab.perm, vec![0, 2, 1]); // (23)
    }

    #[test]
    fn test_inverse_permutation() {
        let p = GroupElement::from_slice(&[1, 2, 0]);
        let inv = p.inverse();
        assert_eq!(inv.perm, vec![2, 0, 1]);
        let id = p.compose(&inv);
        assert_eq!(id.perm, vec![0, 1, 2]);
    }

    #[test]
    fn test_subgroup_trivial() {
        let t = Subgroup::trivial(3);
        assert_eq!(t.order(), 1);
    }

    #[test]
    fn test_subgroup_intersection() {
        let id = GroupElement::identity(3);
        let t12 = GroupElement::from_slice(&[1, 0, 2]);
        let t13 = GroupElement::from_slice(&[2, 1, 0]);
        let s1 = Subgroup::new("s1", &[id.clone(), t12]);
        let s2 = Subgroup::new("s2", &[id, t13]);
        let inter = s1.intersection(&s2);
        assert_eq!(inter.order(), 1);
    }

    #[test]
    fn test_subgroup_generate() {
        let t12 = GroupElement::from_slice(&[1, 0, 2]);
        let sg = Subgroup::generate(&[t12], "gen");
        assert_eq!(sg.order(), 2);
    }

    #[test]
    fn test_s3_subgroup_lattice() {
        let sl = SubgroupLattice::s3_subgroup_lattice();
        assert_eq!(sl.subgroups().len(), 6);
    }

    #[test]
    fn test_s3_lattice_bottom_top() {
        let sl = SubgroupLattice::s3_subgroup_lattice();
        let l = sl.lattice();
        assert_eq!(l.bottom(), Some("trivial"));
        assert_eq!(l.top(), Some("S₃"));
    }

    #[test]
    fn test_s3_lattice_axioms() {
        let sl = SubgroupLattice::s3_subgroup_lattice();
        assert!(sl.lattice().verify_axioms().is_ok());
    }

    #[test]
    fn test_subgroup_contains() {
        let id = GroupElement::identity(3);
        let t12 = GroupElement::from_slice(&[1, 0, 2]);
        let s1 = Subgroup::new("s1", &[id.clone(), t12]);
        let trivial = Subgroup::trivial(3);
        assert!(s1.contains_subgroup(&trivial));
        assert!(!trivial.contains_subgroup(&s1));
    }
}
